on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      bake-convention:
        required: false
        default: 'default'
        type: string

jobs:
  build:
    runs-on:
    - ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - run: |
        dotnet tool install --global Bake --version 0.28.41-beta
        export PATH="$PATH:/home/ubuntu/.dotnet/tools"

        bake run \
          --convention=${{ inputs.bake-convention }} \
          --build-version ${{ inputs.version }} \
          --destination="container>rasmus" \
          --push-container-latest-tag=true'
