on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      bake-convention:
        required: false
        default: 'default'
        type: string
      dockerhub-username:
        required: false
        default: ''
        type: string
    secrets:
      dockerhub-password:
        required: false

jobs:
  build:
    runs-on:
    - ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Bake container
      run: |
        dotnet tool install --global Bake --version 0.29.42-beta
        export PATH="$PATH:/home/ubuntu/.dotnet/tools"

        bake run \
          --convention=${{ inputs.bake-convention }} \
          --build-version ${{ inputs.version }} \
          --destination="container>rasmus" \
          --push-container-latest-tag=true
      env:
        dockerhub_username: ${{ inputs.dockerhub-username }}
        dockerhub_password: ${{ secrets.dockerhub-password }}


