name: pull-requests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline.yaml
    with:
      version: 0.0.${{ github.run_number }}
